// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 12
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){



var __c;(function(){(function(a){__c=a;__c.a="c";__c.b=["google"];__c.c=!0})(function(a){return a["46"]})})();
var __awct;(function(){var a=!1,b=[],c=function(a){var b=p("google_trackConversion"),c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},d=function(){for(;0<b.length;)c(b.shift())},e=function(){return function(){d();a=!1;var b=La["//www.googleadservices.com/pagead/conversion_async.js"];b&&3==b.status&&(La["//www.googleadservices.com/pagead/conversion_async.js"]=void 0)}},f=function(){return function(){d();b={push:c};}};
(function(a){__awct=a;__awct.a="awct";__awct.b=["google"];__awct.c=!0})(function(c){var d={google_conversion_domain:"",google_conversion_id:c["42"],google_conversion_label:c["43"],google_conversion_value:c["44"]||0,google_remarketing_only:!1,onload_callback:c["47"],gtm_onFailure:c["48"]};c[""]&&(d.google_conversion_currency=c[""]);c[""]&&
(d.google_conversion_order_id=c[""]);b.push(d);a||(a=!0,Ba("//www.googleadservices.com/pagead/conversion_async.js",f(),e()))})})();




var nb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ob=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,pb=function(a){if(null==a)return String(a);var b=ob.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},qb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},va=function(a){if(!a||"object"!=pb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!qb(a,"constructor")&&!qb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||qb(a,b)},ta=function(a,b){var c=b||("array"==pb(a)?[]:{}),d;for(d in a)if(qb(a,d)){var e=a[d];"array"==pb(e)?("array"!=pb(c[d])&&(c[d]=[]),c[d]=ta(e,c[d])):va(e)?(va(c[d])||(c[d]={}),c[d]=ta(e,c[d])):c[d]=e}return c};var $a=null,rb=Math.random(),sb=null,ja=null,Ga=!1,tb={},ub={},Ha={};var Ia,Ja,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,
Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf;
(function(){var a=function(a){return{toString:function(){return a}}};vb=a("");wb=a("0");xb="";yb=a("1");zb=a("2");Ab=a("");Bb=a("");Cb=a("");Db=a("");Eb=a("");Fb=a("");Gb=a("5");Hb=a("6");Ib=a("");Jb=a("");Kb=a("");
Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");
$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("7");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");
qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("8");wc=a("");xc=a("9");yc=a("");zc=a("10");Ac=a("11");Bc=a("");Cc=a("12");Dc=a("");Ec=a("13");Fc=a("");Gc=a("");
Hc=a("");Ic=a("");Jc=a("14");Kc=a("");Lc=a("15");Mc=a("");Nc=a("16");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("17");Vc=a("18");Wc=a("");
Xc=a("19");Yc=a("20");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("21");fd=a("");gd=a("");Ia=a("22");hd=a("23");id=a("47");jd=a("48");kd=a("");ld=a("");
md=a("");nd=a("");od=a("");pd=a("");qd=a("");rd=a("24");Ja=a("25");sd=a("");td=a("");ud=a("26");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("27");Dd=a("");Ed=a("");
Fd=a("");Gd=a("");Hd=a("");Id=a("28");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("29");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("30");Td=a("");Ud=a("");Vd=a("");Wd=a("32");Xd=a("");Yd=a("");
Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("33");me=a("");ne=a("");oe=a("");pe=a("");qe=a("34");
re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("35");Ge=
a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("36");
Xe=a("");Ye=a("");Ze=a("");$e=a("");af=a("");bf="";cf=a("");df=a("");ef=a("");ff=a("37");gf=a("38");hf=a("39");jf=a("");kf=a("40");lf=a("");mf=a("");nf=a("");of=
a("");pf=a("");qf=a("");rf=a("");sf=a("")})();var sa=function(a,b){ta(a,b)},jb=function(){},S=function(a){return"function"==typeof a},Xa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},tf=function(a){return"number"==pb(a)&&!isNaN(a)},uf=function(a){return/^[0-9]+$/.test(a)},vf=function(a){return"string"==pb(a)},wf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ia=function(a){return a?a.replace(/^\s+|\s+$/g,""):
""},T=function(a){return Math.round(Number(a))||0},ya=function(a){return"false"==String(a).toLowerCase()?!1:!!a},xf=function(a){var b=[];if(Xa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},G=function(){return new Date},pa=function(a,b){if(!tf(a)||!tf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},yf=function(){this.prefix="gtm.";this.values={}};yf.prototype.set=function(a,b){this.values[this.prefix+a]=b};
yf.prototype.get=function(a){return this.values[this.prefix+a]};yf.prototype.contains=function(a){return void 0!==this.get(a)};
var zf=function(a,b,c){try{if(!a[Hd])return a[Ia](a,b||jb,c||jb);c&&c()}catch(d){}return!1},Af=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ia(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Bf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Cf=function(a){return function(){return a("GTM-KMTMBG")}},Df=function(a){for(var b=0;b<a.length;b++)a[b]()},ua=function(){return"gtm"+Ef()},
Ef=function(){var a=$a.sequence||0;$a.sequence=a+1;return a},wa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ff=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Gf=function(a,b){0==b?a.jb=!0:a.aa=!0;var c=a.i;a.C&&(a.C.Na[c]=b);tb[c]&&(tb[c].state=b)},Hf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var A=window,P=document,Jf=navigator,Fa=function(a,b){var c=A[a];A[a]=void 0===c?b:c;return A[a]},O=function(a,b,c,d){return(d||"http:"!=A.location.protocol?a:b)+c},Kf=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},db=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;db(d,b);c&&(d.onerror=c);Kf(d);return d},da=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Kf(c);db(c,b);void 0!==a&&(c.src=a);return c},F=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},U=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},v=function(a){A.setTimeout(a,
0)},fb=!1,gb=[],Lf=function(a){if(!fb){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){fb=!0;for(var e=0;e<gb.length;e++)v(gb[e])}gb.push=function(){for(var a=0;a<arguments.length;a++)v(arguments[a]);return 0}}},Mf=0,Nf=function(){if(!fb&&140>Mf){Mf++;try{P.documentElement.doScroll("left"),Lf()}catch(a){A.setTimeout(Nf,50)}}},fa=function(a){var b=P.getElementById(a);if(b&&ga(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ga(document.all[a][c],
"id")==a)return document.all[a][c];return b},ga=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Va=function(a){return a.target||a.srcElement||{}},ha=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},mb=function(a){var b=P.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},
Wa=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Of=!1,Pf=[],Qf=function(){if(!Of){Of=!0;for(var a=0;a<Pf.length;a++)v(Pf[a])}},Rf=function(a){a=a||A;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},kb=function(a){window.console&&window.console.log&&window.console.log(a)};var na=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||A.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||A.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:A.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=wf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var n=l[m].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},ma=function(a){var b="";if(a&&a.href)var c=a.href.indexOf("#"),b=0>c?a.href:a.href.substr(0,c);
return b},la=function(a){var b=P.createElement("a");a&&(b.href=a);return b};var Aa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ca=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=na(la(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},R=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},bb=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&
a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c};var Sf=new yf,Tf={},Vf={set:function(a,b){ta(Uf(a,b),Tf)},get:function(a){return W(a,2)},reset:function(){Sf=new yf;Tf={}}},W=function(a,b){if(2==b){var c=a.split(".");for(var f=Tf,e=0;e<c.length;e++){if(void 0===f[c[e]])return;f=f[c[e]]}return f}return Sf.get(a)},Wf=function(a,b){Sf.set(a,b);ta(Uf(a,b),Tf)},Uf=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Xf=!1,Yf=!1;var Zf=Math.random(),$f="0.050000">Zf;
var ag=function(a,b){if($f){var c="//www.googletagmanager.com/a?id=GTM-KMTMBG&cv=12",d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",G().getTime()-T(sb));c+="&sr=0.050000";d("&ps=",Zf);d("&cb=",pa());F(c)}},bg=jb,cg=function(){var a=!1;};var eg=function(a){var b=$a.zones;return b?b.checkState("GTM-KMTMBG",a):dg},dg={active:!0,isWhitelisted:function(){return!0}};var gg=jb,hg=[],ig=!1,qa=function(a){return A["dataLayer"].push(a)},jg=function(a){var b=!1;return function(){!b&&S(a)&&v(Cf(a));b=!0}},kg=function(a){},tg=function(){for(var a=!1;!ig&&0<hg.length;){ig=!0;var b=hg.shift();if(S(b))try{b.call(Vf)}catch(Z){}else if(Xa(b))a:{var c=b;if(vf(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Tf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Z){}}}else{var n=void 0,q=void 0,t=b;for(q in t)t.hasOwnProperty(q)&&Wf(q,t[q]);var w=!1,u=t.event;if(u){t.hasOwnProperty("gtm.uniqueEventId")||(t["gtm.uniqueEventId"]=Ef(),Wf("gtm.uniqueEventId",t["gtm.uniqueEventId"]));
n=t["gtm.uniqueEventId"];ja=u;var z=eg(n);if(z.active){var y=jg(t.eventCallback),D=t.eventTimeout;D&&A.setTimeout(y,Number(D));w=gg(n,u,z.isWhitelisted,y,t.eventReporter)}}sb||(sb=t["gtm.start"])&&bg();var C,K=t,J=n,H=u,L=Tf;ja=null;a=w||a}ig=!1}return!a},ug=function(){var a=tg();try{var b=A["dataLayer"].hide;if(b&&void 0!==b["GTM-KMTMBG"]&&b.end){b["GTM-KMTMBG"]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},vg=function(){var a=Fa("dataLayer",[]),b=Fa("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||
{};gb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Pf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(hg.push.apply(hg,b);300<this.length;)this.shift();return tg()};hg.push.apply(hg,a.slice(0));v(ug)};var Ua=function(a,b,c){U(a,b,c,void 0)},ba=function(a,b,c){r(a,b,c)},La={},Ba=function(a,b,c){var d=La[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.kb:a.Za,d=0;d<c.length;d++)A.setTimeout(c[d],0)}},d={status:1,kb:[],Za:[],cc:void 0};d.Jc=r(a,e(d,2),e(d,3));La[a]=d}0===d.status&&(d.cc(),d.status=2);2===d.status?b():3===d.status?c():1===d.status&&(b&&d.kb.push(b),c&&d.Za.push(c))},ka=function(a,b){return W(a,b||2)},aa=function(a,b){A[a]=b},p=function(a,b,c){var d=
A;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},x=function(a,b,c,d){return(d||"http:"!=A.location.protocol?a:b)+c};var wg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),xg={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},yg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},zg=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};
var mg=function(a){var b=W("gtm.whitelist");var c=b&&zg(xf(b),xg),d=W("gtm.blacklist")||W("tagTypeBlacklist")||[];wg.test(A.location&&
A.location.hostname)&&(d=xf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&zg(xf(d),yg),f={};return function(g){var h=g&&g[Ia];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>wf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>wf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var q;if(!(q=0<=wf(e,h.a)))a:{for(var t=h.b||[],w=new yf,u=0;u<e.length;u++)w.set(e[u],
!0);for(u=0;u<t.length;u++)if(w.get(t[u])){q=!0;break a}q=!1}n=q}return f[h.a]=!k||n}};var _jsm=function(a){if(void 0!==a[ud])try{var b=A.google_tag_manager;return b&&b.e&&b.e(a[ud])}catch(c){}};_jsm.a="jsm";_jsm.b=["customScripts"];var _k=function(a){for(var b=String(W("gtm.cookie")||P.cookie).split(";"),c=0;c<b.length;c++){var d=b[c].split("="),e=ia(d[0]);if(e&&e==a[Nd]){var f=ia(d.slice(1).join("="));return f&&a[Ac]?decodeURIComponent(f):f}}};_k.a="k";_k.b=[];var ea=function(a){var b=P;return Bg?b.querySelectorAll(a):null},Cg=!1;if(P.querySelectorAll)try{var Dg=P.querySelectorAll(":root");Dg&&1==Dg.length&&Dg[0]==P.documentElement&&(Cg=!0)}catch(a){}var Bg=Cg;var _eu=function(a){var b=String(W("gtm.elementUrl")||a[Fc]||""),c=la(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return ja};_e.a="e";_e.b=["google"];var Ig=/(^|\.)doubleclick\.net$/i,Jg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ya=function(a){for(var b=String(P.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=ia(e[0]);if(f&&f==a){var g=ia(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},Kg=function(a,b,c,d,e){if(Ig.test(P.location.hostname)||"/"==c&&Jg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=P.cookie;P.cookie=f;return g!=
P.cookie||0<=wf(Ya(a),b)},Lg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Mg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Ng=function(){var a=na(A.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Og=function(a,b){this.h=a;this.o=b};Og.prototype.toString=function(){var a=""+this.h;1<this.o&&(a=a+"-"+this.o);return a};var Pg=function(a,b){this.La=a;this.ra=b};Pg.prototype.toString=function(){return""+this.ra+"."+this.La};var Sg=function(a,b){var c=new Qg(null,a,b);Rg(c);return c},Qg=function(a,b,c){this.Xa=Math.floor(G().getTime()/864E5);this.qa=b||"auto";this.ha=c||"/";var d=Lg(this.qa),e=Mg(this.ha);this.I=a||new Og(d,e);this.j=[];this.F=new yf},Ug=function(a,b,c){b&&(""==c.La?Tg(a,b):(a.F.contains(b)||a.j.push(b),a.F.set(b,c)))},Vg=function(a,b){for(var c=0;c<b.length;c++)Ug(a,b[c][0],b[c][1])},Tg=function(a,b){var c=wf(a.j,b);0<=c&&a.j.splice(c,1);a.F.set(b,void 0)},Wg=function(a){for(var b=[],c=0;c<a.j.length;c++){var d=
a.j[c];b.push([d,a.F.get(d)])}return b},Xg=function(a){for(var b=0,c=0;c<a.j.length;c++)b=Math.max(b,a.F.get(a.j[c]).ra);return 864E5*b};Qg.prototype.toString=function(){if(0==this.j.length)return"";for(var a=[],b=0;b<this.j.length;b++){var c=this.j[b];a.push(""+c+"."+this.F.get(c).toString())}return"GAX1."+this.I.toString()+"."+a.join("!")};
var Yg=function(a,b){for(var c=new Date,d=Mg(a.ha),e=[],f=0;f<a.j.length;f++){var g=a.j[f];a.F.get(g).ra<a.Xa&&e.push(g)}for(f=0;f<e.length;f++)Tg(a,e[f]);if(a.j.length>(b||10))return!1;c.setTime(Xg(a));if("auto"!=a.qa)return Kg("_gaexp",a.toString(),a.ha,a.qa,c);for(var h=Ng(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.I=new Og(Lg(h[k]),d),Kg("_gaexp",a.toString(),a.ha,h[k],c)))return!0;return!1},Rg=function(a){for(var b=a.I.h,c=a.I.o,d=Ya("_gaexp"),e=[],f=0;f<d.length;f++){var g=Zg(a,d[f]);g&&e.push(g)}Hf(e,
function(a,d){var e=a.I,f=d.I;return e.h==f.h&&e.o==f.o?!1:e.h==b&&e.o==c?!0:f.h==b&&f.o==c?!1:e.h==b?f.h!=b||e.o<f.o:f.h==b?!1:e.o==c?f.h!=b&&(f.o!=c||e.h<f.h):f.o==c?!1:e.h<f.h||e.h==f.h&&e.o<f.o});a.I=0<e.length?e[0].I:new Og(b,c);for(f=e.length-1;0<=f;f--)Vg(a,Wg(e[f]))},Zg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=ia(e[0]);if(0!=f.length){var g=2==e.length?ia(e[1]):"1";if(uf(f)&&uf(g)){d=new Og(T(f),T(g));
break a}}}d=void 0}if(d){for(var h=new Qg(d,a.qa,a.ha),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!uf(m[1]))return;Ug(h,m[0],new Pg(m[2],T(m[1])))}}return h}}};var _v=function(a){var b=W(a[Nd].replace(/\\\./g,"."),a[xc]);return void 0!==b?b:a[Fc]};_v.a="v";_v.b=["google"];var _r=function(a){return pa(a[Ld],a[Jd])};_r.a="r";_r.b=["google"];var _f=function(a){var b=String(W("gtm.referrer")||P.referrer);if(!b)return b;var c=la(b);return b};_f.a="f";_f.b=["google"];var _smm=function(a){var b=a[rd],c=a[Id]||{};return c.hasOwnProperty(b)?c[b]:a[Fc]};_smm.a="smm";_smm.b=["google"];var ch=function(a){var b=A.location,c;(c=a[uc]?a[uc]:W("gtm.url"))&&(b=la(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[fc]&&(f=na(b,a[fc],a[ze],a[Ec],a[me]));return f},_u=ch;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[Gb]).indexOf(String(a[Hb]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[Gb])==String(a[Hb])};_eq.a="eq";_eq.b=["google"];var Za=new String("undefined"),hb=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Za?b:a[d]);return c.join("")}};hb.prototype.toString=function(){return this.resolve("undefined")};hb.prototype.valueOf=hb.prototype.toString;var mh={},ib=function(a,b){var c=Ef();mh[c]=[a,b];return c},nh=function(a){var b=a?0:1;return function(a){var c=mh[a];if(c&&S(c[b]))c[b]();mh[a]=void 0}};var oh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ph=function(a,b){return a<b?-1:a>b?1:0};var qh;a:{var rh=nb.navigator;if(rh){var sh=rh.userAgent;if(sh){qh=sh;break a}}qh=""}var X=function(a){return-1!=qh.indexOf(a)};var th=function(){return X("iPhone")&&!X("iPod")&&!X("iPad")};var uh=function(a){uh[" "](a);return a};uh[" "]=function(){};var wh=function(a,b){var c=vh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var xh=X("Opera"),yh=X("Trident")||X("MSIE"),zh=X("Edge"),Ah;if(Ah=X("Gecko")){var Bh=qh.toLowerCase();Ah=!(-1!=Bh.indexOf("webkit")&&!X("Edge"))}var Ch=Ah&&!(X("Trident")||X("MSIE"))&&!X("Edge"),Dh=qh.toLowerCase(),Eh=-1!=Dh.indexOf("webkit")&&!X("Edge");Eh&&X("Mobile");X("Macintosh");X("Windows");X("Linux")||X("CrOS");var Fh=nb.navigator||null;Fh&&(Fh.appVersion||"").indexOf("X11");X("Android");th();X("iPad");X("iPod");th()||X("iPad")||X("iPod");
var Gh=function(){var a=nb.document;return a?a.documentMode:void 0},Hh;a:{var Ih="",Jh=function(){var a=qh;if(Ch)return/rv\:([^\);]+)(\)|;)/.exec(a);if(zh)return/Edge\/([\d\.]+)/.exec(a);if(yh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Eh)return/WebKit\/(\S+)/.exec(a);if(xh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Jh&&(Ih=Jh?Jh[1]:"");if(yh){var Kh=Gh();if(null!=Kh&&Kh>parseFloat(Ih)){Hh=String(Kh);break a}}Hh=Ih}
var Lh=Hh,vh={},Mh=function(a){return wh(a,function(){for(var b=0,c=oh(String(Lh)).split("."),d=oh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=ph(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||ph(0==k[2].length,0==l[2].length)||ph(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Nh;
var Oh=nb.document;Nh=Oh&&yh?Gh()||("CSS1Compat"==Oh.compatMode?parseInt(Lh,10):5):void 0;var Ph;if(!(Ph=!Ch&&!yh)){var Qh;if(Qh=yh)Qh=9<=Number(Nh);Ph=Qh}Ph||Ch&&Mh("1.9.1");yh&&Mh("9");var lb=function(a,b){var c="";yh&&!Rh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Sh)a.srcdoc=d;else if(Th){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Uh(a,d)},Sh=Eh&&"srcdoc"in document.createElement("iframe"),Th=Ch||Eh||yh&&Mh(11),Uh=function(a,b){yh&&Mh(7)&&!Mh(10)&&6>Vh()&&Wh(b)&&(b=Xh(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};yh&&!Rh(a)?Yh(a,c):c()},Vh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Rh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{uh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Zh=0,Yh=function(a,b){var c="goog_rendering_callback"+Zh++;nb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Wh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Xh=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var eb;var _img=function(a,b,c){var d=mb('<a href="'+a[ff]+'"></a>')[0].href,e=a[Lb];if(e)var f=d.charAt(d.length-1),g=0<=d.indexOf("?")?"?"==f||"&"==f?"":"&":"?",d=d+(g+e+"="+a[Mb]);F(d,b,c)};_img.a="img";_img.b=["customPixels"];
var ni=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=ki(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=li(f,g);mi(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},oi=null,ki=function(a){if(oi)return oi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return oi=
c}0==a.styleSheets.length&&a.createStyleSheet();return oi=a.styleSheets[0]},li=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},mi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var vi={},wi=void 0,xi=function(a){var b=vi[a];b||(b={id:a,w:[],da:0,Pa:null,Da:void 0,Ia:!1},vi[a]=b);wi=b},zi=function(a,b,c,d){var e=wi;if(!Bg||!e)return!1;var f={id:e.id+":"+e.w.length,sb:b,Z:[],nb:c,J:a,za:0,wa:d||null,Wa:0,ca:!1};e.w.push(f);null===a?(f.ca=!0,b(null)):yi(e);return!0},Ai=function(a){var b=ni(a,"visibility","hidden",!0);return function(){S(b)&&b.apply();b=null}},Bi=function(a,b,c,d){var e=b;if(!fb){var f=Ai(a.B);gb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return zi(a,
e,c,d)},yi=function(a){if(!a.Ia){for(var b=a.da;b<a.w.length;b++){var c=a.w[b],d=b==a.da;if(!c.ca&&!Ci(d,c))break;c.ca&&d&&a.da++}a.w.length>a.da?(a.Pa||(a.Pa=A.setTimeout(function(){a.Pa=null;yi(a)},80)),fb||a.Da||(a.Da=function(){v(function(){yi(a)})},U(P,"DOMContentLoaded",a.Da))):Di(a)}},Di=function(a){for(var b=0;b<a.w.length;b++){var c=a.w[b];if(c.J)for(var d=ea(c.J.B)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Ei(f,c.id),c.Z.push(Fi(f,c.id)))}}},
Ci=function(a,b){var c=[];if(b.J){var d=Gi(b.J,b.id),e=null;b.wa&&(e=Gi(b.wa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!fb&&(null===b.wa.u||b.Wa+c.length<b.wa.u)))break;c.push({element:g,gc:h})}}if(!fb&&b.nb&&(!a||null==b.J.u||b.J.u!=b.za+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].gc,n;b.za++;Ei(l,b.id);m&&(b.Wa++,n=b.id+"-t",Ei(m,n));var q=b.sb(l,m);S(q)&&b.Z.push(q);b.Z.push(Fi(l,b.id));m&&n&&b.Z.push(Fi(m,n))}if(b.J.u&&
b.J.u==b.za||fb)b.ca=!0;return!0},Ei=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Fi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Gi=function(a,b){for(var c=ea(a.B)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.H&&!Hi(f))break;d.push(f)}}return d},Hi=function(a){if(fb)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ma,Ii,Ji,Sa=/(Firefox\D28\D)/g.test(Jf.userAgent),Li=function(a,b){return function(c){var d;c=c||A.event;var e=Va(c),f=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(e=Wa(e,["a","area"]),f=!e||!e.href||Ki(e.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var g="FORM_SUBMIT"==a?Ma:Ji;if(c.defaultPrevented||!1===c.returnValue||c.ea&&c.ea()){if(e){d={simulateDefault:!1};var h=Na(g,["wnc","nwnc"]);h&&Oa(a,e,d,g.wt,h)}}else{if(e){d={};var k,l=
Na(g,["wnc","nwnc","nwc","wc"]);(k=Oa(a,e,d,g.wt,l))||(Pa(d.eventReport,g)?b=!0:f=!0);f=f||k||"LINK_CLICK"==a&&Sa;d.simulateDefault=!k&&b&&!f;d.simulateDefault&&(f=Ta(e,d)||f,!f&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||f;return c.returnValue}return!0}}}},Oa=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||ga(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";
g.event="gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Mi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Ni(b);g.eventTimeout=f;g.eventCallback=Oi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return qa(g)},
Ni=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},Ra=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Ta=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Jf.userAgent),e=Ra(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=A.frames&&A.frames[f]||A[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+G().getTime(),b.targetWindow=A.open("",b.targetWindowName));break;default:d&&!A.frames[e]?(b.simulateDefault=!1,c=!0):(A.frames[e]||(b.targetWindowName=e),b.targetWindow=A.frames[e]||A.open("",e))}return c},Mi=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||G().getTime(),500>G().getTime()-c&&A.setTimeout(Mi(a,b,c),25)))}},Oi=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;Qa(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||G().getTime(),500>G().getTime()-c&&A.setTimeout(Oi(a,b,c),25)}},Na=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Pi=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Pa=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Qi.length;c++)if(a.passingRules[c]){var d=Ri[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Qi[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},oa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Va(a);b&&Oa("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Ii&&(Ii=ma(P.location));Pi(Ji,b||!1,c||!1,d,e);if(P.gtmHasLinkClickListenerTag)return;
P.gtmHasLinkClickListenerTag=!0;f="click";g=Li(a,b||!1);break;case "FORM_SUBMIT":Pi(Ma,b||!1,c||!1,d,e);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";g=Li(a,b||!1);break;default:return}U(P,f,g,h)},Ki=function(a){if(!Ii)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=la(a);return Ii==ma(c)},Qa=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit},Si=function(){var a=function(a){var b=Fa("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Ji=a("linkClickMap");Ma=a("formSubmitMap")};
var Wi=function(a,b,c){var d,e=encodeURIComponent,f=(a[kf]?"//ad.doubleclick.net/activity":"//"+e(a[zb])+".fls.doubleclick.net/activityi")+";src="+e(a[zb])+";type="+e(a[hd])+";cat="+e(a[yb]);a[nf]&&(f+=";u="+e(a[nf]));a[af]&&(f+=";tran="+e(a[af]));var g=a[vc]||{},h;for(h in g)g.hasOwnProperty(h)&&(f+=";"+e(h)+"="+e(g[h]));f+=";qty="+e(a[le])+";cost="+e(a[qe])+";ord="+e(a[Wd]);if(a[Vc]){var f=f+";prd=",k=function(a){for(var b=
[],c=0;c<a.length;c++){var d=c+1;b.push("i"+d+":"+e(a[c].id),"p"+d+":"+e(a[c].price),"q"+d+":"+e(a[c].quantity));a[c].country&&b.push("c"+d+":"+e(a[c].country));a[c].language&&b.push("l"+d+":"+e(a[c].language));a[c].accountId&&b.push("a"+d+":"+e(a[c].accountId))}return b.join("|")};if(a[gf])d=W("ecommerce.purchase.products",2)||[],f+=k(d);else if(a[vd])d=a[je]||[],f+=k(d);else if(a[ye]){for(var l=(a[je]||"").split("|"),m=0;m<l.length;m++){var n=l[m].split(":");n[1]=n[1]&&e(n[1])||"";l[m]=n.join(":")}f+=
l.join("|")}}if(a[Tc]){var q=a[Jb]||[];if(0<q.length){r("//www.gstatic.com/attribution/collection/attributiontools.js",function(){Wi.Ja(a,f,q,b,c)},c);return}}Wi.fa(a,f,b,c)};Wi.Ja=function(a,b,c,d,e){for(var f={},g=0;g<c.length;g++){var h=c[g];h.hasOwnProperty("key")&&h.hasOwnProperty("value")&&(f[h.key]=h.value)}var k=[];k.push(f);b+=A.google_attr.build(k);Wi.fa(a,b,d,e)};Wi.fa=function(a,b,c,d){var e=ch({});!a[kf]&&e&&(";"!=
!b.charAt(b.length-1)&&(b+=";"),b+="~oref="+encodeURIComponent(e));(a[kf]?F:da)(b+"?",c,d)};var _fls=Wi;_fls.a="fls";_fls.b=[];var Ea=function(a,b){var c=b||nb,d=c.onerror,e=!1;Eh&&!Mh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,cb:h,zc:k,error:l});return e}};var mj=function(a){if(!a)return!1;if(a[Fb]&&Xa(a[Hb])){for(var b=a[Hb],c=0;c<b.length;c++)if(a[Hb]=b[c],zf(a))return!0;return!1}return zf(a)};
var nj=[],oj={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},pj=function(a){return oj[a]},qj=/[\x00\x22\x26\x27\x3c\x3e]/g;nj[3]=function(a){return String(a).replace(qj,pj)};var uj=/[\x00\x08-\x0d\x22\x26\x27\/\x3c-\x3e\\\x85\u2028\u2029]/g,vj={"\x00":"\\x00","\b":"\\x08","\t":"\\t","\n":"\\n","\x0B":"\\x0b",
"\f":"\\f","\r":"\\r",'"':"\\x22","&":"\\x26","'":"\\x27","/":"\\/","<":"\\x3c","=":"\\x3d",">":"\\x3e","\\":"\\\\","\u0085":"\\x85","\u2028":"\\u2028","\u2029":"\\u2029",$:"\\x24","(":"\\x28",")":"\\x29","*":"\\x2a","+":"\\x2b",",":"\\x2c","-":"\\x2d",".":"\\x2e",":":"\\x3a","?":"\\x3f","[":"\\x5b","]":"\\x5d","^":"\\x5e","{":"\\x7b","|":"\\x7c","}":"\\x7d"},wj=function(a){return vj[a]};
var Cj=/['()]/g,Dj=function(a){return"%"+a.charCodeAt(0).toString(16)};nj[12]=function(a){var b=
encodeURIComponent(String(a));Cj.lastIndex=0;return Cj.test(b)?b.replace(Cj,Dj):b};var Ej=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Fj={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10",
"\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86",
"\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB","\uff3d":"%EF%BC%BD"},Gj=function(a){return Fj[a]};var Hj=
/^(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i;nj[14]=function(a){var b=String(a);return Hj.test(b)?b.replace(Ej,Gj):"#zSoyz"};var Ij=122,Jj=[],Kj=[],ng=[],Lj=new yf,Mj=[],Y=[],Qi=[],Ri=[],Nj=function(){this.P=[]};Nj.prototype.set=function(a,b){this.P.push([a,b]);return this};Nj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.P.length;d++){var e=qg(this.P[d][0],a,b),f=qg(this.P[d][1],a,b);c[e]=f}return c};var Oj=function(a){this.index=a};Oj.prototype.resolve=function(a,b){var c=ng[this.index];if(c&&!b(c)){var d=c[Ja];if(a){if(a.get(d))return;a.set(d,!0)}c=qg(c,a,b);a&&a.set(d,!1);return zf(c)}};
var _M=function(a){return new Oj(a)},Pj=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=qg(Jj[a[f]],b,c);g===Za&&(e=!0);d.push(g)}return e?new hb(d):d.join("")}},_T=function(a){return new Pj(arguments)},Qj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=qg(a[0],c,d);if(a[0]instanceof Oj&&b(8)&&b(16)){if(e===Za)return e;var f=ua();Lj.set(f,e);return'google_tag_manager["GTM-KMTMBG"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=nj[a[g]](e);return e}},_E=function(a,b){return new Qj(arguments)},Rj=function(a,b){this.A=a;this.la=b},_R=function(a,b){return new Rj(a,b)};
var qg=function(a,b,c){var d=a;if(a instanceof Oj||a instanceof Nj||a instanceof Pj||a instanceof Qj)return a.resolve(b,c);if(!(a instanceof Rj))if(Xa(a))for(var d=[],e=0;e<a.length;e++)d[e]=qg(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=qg(a[f],b,c))}return d},Uj=function(){for(var a=[_jsm,'all.AdBlockEnabled','(function(){var a\x3ddocument.createElement(\x22ins\x22);a.className\x3d\x22AdSense\x22;a.style.display\x3d\x22block\x22;a.style.position\x3d\x22absolute\x22;a.style.top\x3d\x22-1px\x22;a.style.height\x3d\x221px\x22;document.body.appendChild(a);var b\x3d!a.clientHeight;document.body.removeChild(a);return b})();',_T(2),_eq,_e,'_event',_M(1),'gtm.js','1637265_2147479553',_ua,true,_smm,'gtm.googleAnalyticsTrackingId',_v,'all.environment',2,_M(2),'Development','Test','Production','UA-27713149-7','UA-68934571-1',{18:21,19:21,20:22},_M(3),'1','2','4','5','6',_M(0),'all.abTesting',_M(4),'receipt.hasKomplettCard',_M(5),'receipt.deliveryMethod',_M(6),'receipt.paymentMethod',_M(7),{25:30,26:32,27:34,28:36,29:38},false,'\x26uid','allowLinker','all.customerNumber',_M(8),'false',{41:44,42:45},'\x26tid','\x26cd1','\x26cd2','\x26cd4','\x26cd5','\x26cd6',{47:24,48:30,49:32,50:34,51:36,52:38,41:44,42:45},7,_k,'gtm.carma.cookieValue','c_rid',_M(9),'undefined',_cn,'all.pageType',_M(10),'Confirmation','receipt.transactionTotalWithoutFreight',_M(11),'1637265_6',_img,__c,'gtm.carma.serverUrl','https://www2.carmamail.com/mail/roi',_E(_M(12),14,3),'?ts\x3d',_r,'Random Number',_E(_M(13),12),'\x26rid\x3d',_E(_M(9),12),'\x26amount\x3d',_E(_M(11),12),_T(71,72,75,76,77,78,79),11,'1637265_2','1637265_11','1637265_12',_fls,'gtm.advertiserId','0','5372319',{18:87,19:87,20:88},_M(14),'purch0','order0','transactionId',_M(15),'transactionTotal',_M(16),'u4','u5','u6','NO','NOK',{97:100,98:101,99:96},12,'checkoutOption','1637265_8','Ecommerce','Checkout Option','\x26t','\x26ec','\x26ea','\x26ni','event',{47:24,108:112,109:106,110:107,111:40},13,__awct,'882412641','7eZWCKK5yGoQ4ZjipAM',_u,'_url',_M(17),14,'all.customerType','gtm.checkoutPlatform','Midas','gtm.icsSellerId','gtm.icsUrl','//t.ics0.com/ics_test','//t.ics0.com/ics',{18:127,20:128,19:127},'receipt.icsProducts','receipt.icsTimeStamp','receipt.icsVisitGuid','receipt.transactionTotalNet','transactionProducts','url','path',[]],b=[],c=0;c<a.length;c++)b[c]=
Tj(c,a);return b},Tj=function(a,b){var c=b[a],d=c;if(c instanceof Oj||c instanceof Qj||c instanceof Pj||c instanceof Rj)d=c;else if(Xa(c))for(var d=[],e=0;e<c.length;e++)d[e]=Tj(c[e],b);else if("object"==typeof c){var d=new Nj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Tj(c[f],b))}return d},Wj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Jj[e[1]]);if(1==a)for(var f=Vj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Kj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Vj(e[g]);3==a&&(c[d]=Jj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Jj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Vj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Ij;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);
2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Xj=function(a,b,c){a.push.apply(a,Wj(b,c))};var Yj;
var pg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=bk[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},ek=function(a){},fk=function(a,b){},sg=function(a){};var gk,hk;
var tk=function(a){return function(){}},uk=function(a){return function(){}};var vk=function(a){var b=this;this.i=a;this.aa=this.jb=!1;this.va=[];this.sa=[];this.X=function(){b.aa||Df(b.va);Gf(b,1);if(ub[a])for(var c=0;c<ub[a].length;c++)ub[a].shift().X()};this.W=function(){b.aa||Df(b.sa);Gf(b,2);if(ub[a])for(var c=0;c<ub[a].length;c++)ub[a].shift().W()};this.D=jb},wk=function(a,b){a.va.push(b)},xk=function(a,b){a.sa.push(b)},yk=function(a){this.L=[];this.Ma=[];this.Ya={};this.eb=[];this.V=0;this.Ka={};this.Oa={};this.Na={};this.event=a};yk.prototype.addListener=function(a){this.eb.push(a)};
var zk=function(a){0<a.V||Df(a.eb)},Ak=function(a,b,c,d,e,f){if(!c.aa){a.L[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=Xa(d)?d.slice():["or",d];e=Xa(e)?e.slice():[e];f=Xa(f)?f.slice():[f];a.Ya[b]=d;a.Ka[b]=0<e.length;a.Oa[b]=0<f.length;a.V++;var g=function(){0<a.V&&!a.Ka[b]&&!a.Oa[b]&&a.V--;zk(a)};wk(c,g);xk(c,g)}},Fk=function(a){for(var b=[],c={},d=0;d<a.L.length;c={R:c.R},d++)if(c.R=a.L[d],c.R){var e=a.Ya[d],f=a.Ka[d],g=a.Oa[d];if(0!=e.length||f||g){if(0<e.length)for(var h=Bk(e,
c.R.D),k=0;k<e.length;k++)e[k]instanceof Rj&&e[k].A!=d&&Ck(a,e[k].A,h);(f||g)&&Dk(a,d,function(a){return function(){0<a.R.C.V&&a.R.C.V--;zk(a.R.C)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.L[b[d]].D();for(d=0;d<a.Ma.length;d++){var l=a.Ma[d];Ek(l);0<l.length&&l[0].D()}},Ck=function(a,b,c){a.L[b]&&(wk(a.L[b],function(){c(b,!0)}),xk(a.L[b],function(){c(b,!1)}))},Bk=function(a,b){var c=jb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof Rj&&a[h].A===e||a[h]===e){g=
h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Dk=function(a,b,c){var d,e=[],f=!1,g=function(b){var c,d,h=Y[b];if(a.event.f(h)){}else d=Gk(h,b,a.event.f,a);if(c=d){var k=Hk(b,!0);0<k.length&&g(k[0].A);e.push(c);var l=Hk(b,!1);0<l.length&&g(l[0].A)}else f=
!0};g(b);if(!f){for(var h=0;h<e.length;h++){var k=e[h],l=Hk(k.i,!0);if(0<l.length){var m=e[h-1];d=Ik(k);wk(m,d);0==l[0].la?xk(m,d):xk(m,c)}var n=Hk(k.i,!1);0<n.length&&(d=Ik(e[h+1]),wk(k,d),0==n[0].la?xk(k,d):xk(k,c))}wk(e[e.length-1],c);xk(e[e.length-1],c);a.Ma.push(e)}},Hk=function(a,b){var c=b?we:Ne,d=Y[a],e=void 0===d[c]?[]:d[c];return Xa(e)?e:[e]},Ik=function(a){return function(){a.D()}},Ek=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=tb[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.C.Na[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=Hk(a[c+1].i,!0);if(0<h.length&&1==h[0].la)for(++c;c<a.length;c++)b.push(a[c])}}var k=Jk(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,q=k[l],t=q[0],w=q[q.length-1],u,z=0;z<a.length;z++){var y=a[z];!m&&y.i==t&&0<z&&(m=a[z-1]);y.i==w&&z<a.length-1&&(n=a[z+1]);if(-1<wf(q,y.i))if(u=a.splice(z,1)[0],y.i==w)break;else z--}if(u){var D=Number(l),C=m,K=n;if(C){var J=C.va[0],H=C.sa[0],L=C;L.va=[];L.sa=
[];wk(C,J);xk(C,H)}if(C&&K){var B=Ik(K);wk(C,B);var I=Hk(C.i,!1);0<I.length&&I[0].A!=D&&0==I[0].la&&xk(C,B);var M=Hk(K.i,!0);0<M.length&&M[0].A!=D&&0==M[0].la&&xk(C,B)}}}},Jk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Hk(a,!0);0<b.length&&f(b[0].A);e.push(a);var c=Hk(a,!1);0<c.length&&f(c[0].A)};f(d.i);b[d.i]=e}Kk(a,b);return b},Kk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<wf(b[e],d)){delete b[d];break}}};var Lk=function(a,b,c){return function(){a[id]=b.X;a[jd]=b.W;var d=b.i,e=b.C&&b.C.Na[d],f=tb[d]&&tb[d].state,g=e?void 0!==e:b.jb||b.aa,h=tb[d]&&tb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Gf(b,0);var m=b.C?b.C.event:void 0,n=a,n=qg(n,new yf,c);a=n;if(m){}zf(a,b.X,b.W)}else k&&0==f||l&&0==e?ub[d].push(b):k&&1==f||l&&1==e?b.X():b.W()}},Gk=function(a,b,c,d){var e=d&&d.L,f;if(f=e)a:{if(e&&Xa(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].i===b){f=e[g];break a}f=void 0}var h=f||new vk(b);h.C=d;wk(h,tk(a));xk(h,uk(a));h.D=Lk(a,h,c);return h};
var Qk=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=u+b[0];A[t()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!va(b))return!1;for(var e=wa(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;if(a[Nc]){c=W("ecommerce");
}else a[Mc]&&(c=a[Mc].ecommerce);if(!va(c))return;c=Object(c);var e=wa(a[ed],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=
c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&q[e]||!c&&void 0===q[e])){var f=n[e]?ya(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}var l,m,n,q;Fa("GoogleAnalyticsObject",a[Nd]||"ga");var t=function(){return A.GoogleAnalyticsObject},w=Fa(t(),function(){var a=A[t()];a.q=a.q||[];a.q.push(arguments)});
w.l=Number(G());var u="",z="";"string"!=typeof a[$e]?(z=ua(),u=z+"."):""!==a[$e]&&(z=a[$e],u=z+".");var y=!1;q={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0},n={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,
legacyHistoryImport:!0,nonInteraction:!0,useBeacon:!0};var D={name:z};k(a[ed],D,!0);w("create",a[wb],D);d("set","&gtm","GTM-KMTMBG");e("nonInteraction",Sd);g("dimension",a[Jc]);var C={};k(a[ed],C,!1)&&d("set",C);var K;a[Cd]&&d("require","linkid","linkid.js");
d("set","hitCallback",function(){if(S(a[kd]))a[kd]();else{var c=a[ed],d=c&&c.hitCallback;S(d)&&d()}b()});if(a[We]){a[Uc]&&(d("require","ec","ec.js"),h()),m={hitType:"event",eventCategory:String(a[Yc]),eventAction:String(a[Xc]),eventLabel:f(String,a[Zc]),eventValue:f(T,a[$c])},k(K,
m,!1),d("send",m);}else if(a[Xe]){}else if(a[Ze]){}else if(a[Ye]){}else if(a[Dc]){}else if(a[Bc]){}else if(a[Ve]){}else{a[Uc]&&(d("require","ec","ec.js"),h());a[Lc]&&!a[Wc]&&(l="_dc_gtm_"+String(a[wb]).replace(/[^A-Za-z0-9-]/g,
""),d("require","displayfeatures",void 0,{cookieName:l}));K?d("send","pageview",K):d("send","pageview");}if(!Qk){var E=a[zc]?"u/analytics_debug.js":"analytics.js";a[sd]&&!a[zc]&&(E="internal/"+E);Qk=!0;r(O("https:","http:","//www.google-analytics.com/"+E,y),function(){A[t()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Rk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Mj[b]&&qg(Mj[b],new yf,c),e=d;d&&(e=mj(d));a[b]=[e,d]}return a[b]}},Sk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.U(c[d],a.f)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.U(e[d],a.f)[0])return!1;return!0},Tk=function(a){for(var b=new yk(a),c=0;c<Ij;c++)if(a.ya[c]&&!a.Ha[c])if(a.f(Y[c])){}else{var d=a.ia[c],e=Gk(d,c,a.f,b);Ak(b,c,e,d[Gc],d[we],d[Ne]);if(d[vb])break}b.addListener(a.oa);Fk(b);zk(b)},Uk=!1,gg=function(a,b,c,d,e){switch(b){case "gtm.js":if(Uk)return!1;Uk=!0;break;case "gtm.sync":if(W("gtm.snippet")!=rb)return!1}for(var f={id:a,name:b,oa:d||jb,ya:Vj(),Ha:Vj(),U:Rk(),f:mg(c)},g=[],h=0;h<Qi.length;h++)if(Sk(f,Qi[h])){g[h]=!0;for(var k=
f,l=Qi[h],m=l[1],n=0;n<m.length;n++)k.ya[m[n]]=!0;for(var q=l[3],n=0;n<q.length;n++)k.Ha[q[n]]=!0}else g[h]=!1;var M=[];for(var V=0;V<Ij;V++)if(f.ya[V]&&!f.Ha[V])if(f.f(Y[V])){}else{M[V]=Y[V];}f.ia=M;Tk(f);e&&S(e)&&e({passingRules:g,resolvedTags:f.ia});if("gtm.js"==b||"gtm.sync"==b)a:{}for(var Q in f.ia)if(f.ia.hasOwnProperty(Q)){var za=f.ia[Q],
Z;if(!(Z=void 0==za[Ja])){var Qb=za[Ja];Z=!("function"!=typeof String.prototype.startsWith?0===Qb.indexOf("_implicit"):Qb.startsWith("_implicit"))}if(Z)return!0}return!1};var Wk=function(){};var Xk=function(){};var Vk={macro:function(a){if(Lj.contains(a))return Lj.get(a)}};Vk.dataLayer=Vf;Vk.onHtmlSuccess=nh(!0);Vk.onHtmlFailure=nh(!1);Vk.callback=function(a){Ha.hasOwnProperty(a)&&S(Ha[a])&&Ha[a]();delete Ha[a]};
Vk.zb=function(){var a=A.google_tag_manager;a||(a=A.google_tag_manager={});$a=a;if(a["GTM-KMTMBG"]){var b=$a.zones;b&&b.registerNatural("GTM-KMTMBG")}else{a["GTM-KMTMBG"]=Vk;Si();Jj.push.apply(Jj,Uj());Xj(Kj,0,"22:0,25:1,26:3,22:4,22:5,25:6,5:7,6:8,22:10,31:11,22:12,25:13,22:14,25:15,29:15,9:16,24:17,28:23,0:24,17:11,16:11,25:31,29:31,25:33,29:33,25:35,29:35,25:37,29:37,14:39,39:40,25:43,29:43,21:46,10:40,12:40,3:53,27:40,15:11,35:54,22:55,25:56,29:57,11:11,5:58,6:59,22:60,25:61,29:61,5:62,6:63,25:64,29:64,5:65,22:67,22:68,25:69,41:25,46:70,22:73,25:74,37:80,35:81,5:17,6:18,6:19,22:85,25:86,28:89,2:90,23:91,1:92,25:93,29:93,32:94,25:95,29:95,34:96,8:102,33:25,40:40,18:11,38:11,35:103,6:104,36:11,4:11,20:106,19:107,30:40,3:113,15:40,35:114,22:115,44:96,42:116,43:117,22:118,25:119,45:120,35:121,25:122,29:122,25:123,46:124,25:125,46:87,25:126,28:129,25:130,29:130,25:131,29:131,25:132,29:132,25:133,29:133,25:134,29:134,25:135,7:136,13:137");Xj(ng,1,"H,w,AAP,Aww,AAJY,AAJgB,AAJAG,AAJAY,AAJAAG,AAAAAAwD,AAJAAAAgB,AAJAAAAAY,AAAAAAAAAe,AAAAAAAAAgB,AQQAAAAAAAAG,AAJAAAAAAAAAD,AAJAAAAAAAAAY,AAAAAAAAAAAAAAAAG,AAJAAAAAAAAAAAAAgB,AAAAAAAAAKAAAAAAAG,AAAAAAAAAKAAAAAAAY,AQQAAAAAAAAAAAAAAgB,AAJAAAAAAAAAAAAAAAG,AAJAAAAAAAAAAAAAAAY,AAJAAAAAAAAAAAAAAAgB,AAJAAAAAAAAAAAAAAAAG,AAJAAAAAAAAAAAAAAAAY,AAAAAAAAAAAAAAAACAAgD");Xj(Mj,1,"ID,IAAAAAAM,AAAAAAAQG,IAAAAAAIg,IAAAAAAAAAY,IAAAAAAAAAo,IBAAAAAAAAAAAAB");Xj(Y,1,"AMAHg5P,AIAAAAAAABG,AIAAAAAAAAA5k_,AMAHAQCAAAAAAA-H,AIAAAAAAAIAAAAA4Z");Xj(Qi,2,"B:B::,F:C:K:,F:U::,AB:I::,R:::U,h:::U");Xj(Ri,4,"9:,66:,82.82:,105:,:83.83,:84.84");for(var c=0;c<Y.length;c++){var d=Y[c],
e=1;d[Ud]?e=2:d[ef]&&(e=0);tb[c]={firingOption:e,state:void 0};ub[c]=[]}cg();vg();var n=A;if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)Lf();else{U(P,"DOMContentLoaded",Lf);U(P,"readystatechange",Lf);if(P.createEventObject&&P.documentElement.doScroll){var q=!0;try{q=!n.frameElement}catch(t){}q&&Nf()}U(n,"load",Lf)}"complete"===P.readyState?Qf():U(A,"load",Qf);Xk();Wk();}};Vk.zb();var _vs="res_ts:1481892317965000,srv_cl:159707852,ds:live,cv:12";
})()
